#!/usr/bin/env python3
"""Apply the logged edits to the original manuscripts/guides and write the edited masters.

    original/<lang>.md  --(mechanical cleanup)-->  --(edits/<which>-<lang>.json)-->  <lang>.md

Each edit must match exactly once (or `count` times). Spaces in `find` match any normal or
non-breaking space, so edits are written with plain spaces. A change log is written to
docs/EDIT_LOG.md. Nothing is changed silently: an edit that does not match stops the run.
"""
import json
import re
import sys
from pathlib import Path

# usage: python3 tools/apply_edits.py [book-slug]   (default: ananya-stolen-flame)
BOOK = Path(__file__).resolve().parents[1] / "books" / (sys.argv[1] if len(sys.argv) > 1 else "ananya-stolen-flame")
def _title() -> str:
    try:
        return json.loads((BOOK / "book.json").read_text(encoding="utf-8"))["titles"]["en"]["title"]
    except (OSError, KeyError, ValueError):
        return BOOK.name
TITLE = _title()


def load_normalizer():
    """Optional books/<slug>/normalize.py: structure-only conversion of the supplied files to the canonical shape."""
    f = BOOK / "normalize.py"
    if not f.exists():
        return None
    import importlib.util
    spec = importlib.util.spec_from_file_location(f"normalize_{BOOK.name}", f)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod
SP = "[   ]"


def mechanical(text: str, lang: str) -> tuple[str, dict]:
    stats = {}
    n_before = len(re.findall(r"\\[!.$]", text))
    text = re.sub(r"\\([!.$])", r"\1", text)
    stats["markdown escapes removed"] = n_before
    c = len(re.findall(r"(?<=\w)'(?=\w)", text))
    text = re.sub(r"(?<=\w)'(?=\w)", "’", text)
    stats["straight apostrophes → ’"] = c
    t2 = re.sub(r"[ \t]+\n", lambda m: m.group(0) if m.group(0).startswith("  \n") and False else "\n", text)
    stats["trailing spaces trimmed"] = len(text) - len(t2)
    return t2, stats


def pattern(find: str, regex: bool):
    if regex:
        return re.compile(find.replace(" ", SP), re.S)
    out = []
    for ch in find:
        out.append(SP if ch == " " else re.escape(ch))
    return re.compile("".join(out))


def apply(which: str, lang: str, log: list):
    src = BOOK / which / "original" / f"{lang}.md"
    text = src.read_text(encoding="utf-8")
    text, stats = mechanical(text, lang)
    log.append(f"\n### {which.title()} · {lang.upper()} — mechanical cleanup\n")
    for k, v in stats.items():
        log.append(f"- {k}: {v}")
    norm = load_normalizer()
    if norm:
        text = norm.normalize(text, lang, which)
        note = getattr(norm, "NOTE", "structure normalized to the canonical layout, no wording changed")
        log.append("- %s: `books/%s/normalize.py`" % (note, BOOK.name))
    ep = BOOK / "edits" / f"{which}-{lang}.json"
    if ep.exists():
        log.append(f"\n### {which.title()} · {lang.upper()} — edits\n")
        log.append("| id | type | before | after | why |\n|---|---|---|---|---|")
        for e in json.loads(ep.read_text(encoding="utf-8")):
            pat = pattern(e["find"], e.get("regex", False))
            n = len(pat.findall(text))
            want = e.get("count", 1)
            if n != want:
                raise SystemExit(f"[{which} {lang}] {e['id']}: expected {want} match(es), found {n}: {e['find'][:70]!r}")
            m = pat.search(text)
            before = m.group(0)
            if e.get("regex"):
                text = pat.sub(e["replace"], text)
            else:
                text = pat.sub(lambda _m: e["replace"], text)
            sh = lambda s: s.replace("\n", " ⏎ ").replace("|", "\\|").strip()[:160] or "(deleted)"
            log.append(f"| {e['id']} | {e['kind']} | {sh(before)} | {sh(e['replace'])} | {e['why']} |")
    out = BOOK / which / f"{lang}.md"
    out.write_text(text, encoding="utf-8")
    return text


def main():
    log = [f"# Edit log: {TITLE} (EN · FR · ES)\n",
           "Generated by `tools/apply_edits.py`. Every change to the supplied manuscripts and guides is listed here; "
           "the verbatim originals are kept in `manuscript/original/` and `guide/original/`.\n"]
    for which in ("manuscript", "guide"):
        for lang in ("en", "fr", "es"):
            apply(which, lang, log)
    (BOOK / "docs" / "EDIT_LOG.md").write_text("\n".join(log) + "\n", encoding="utf-8")
    print("edited masters written; log -> docs/EDIT_LOG.md")


if __name__ == "__main__":
    main()
