"""Structure normalizer for The Drum and the Ball (EN / FR / ES).

The supplied manuscripts follow the canonical shape (h1 title, h2 parts / epilogue / glossary / note, h3 chapters, an
italic date line under each chapter) with a few structural slips that are repaired here. No wording is touched:

* English and Spanish carry the contents as a bold line followed by bold lines; the canonical shape is an h2 "Contents"
  heading (the list itself is regenerated by the build, never copied);
* the French file separates chapters with `---` rules; the other two do not;
* the French glossary sets each term on its own line (hard line break); English and Spanish use "**Term**: definition"
  on one line, as in the other volumes, so French follows;
* chapter 13: the three promises are a numbered list in French and Spanish, plain paragraphs in English; English
  becomes the same numbered list;
* English glossary: “Pagne” stands after “Pirogue”; the French and Spanish glossaries are alphabetical, so English is too.

The same alphabetical slip is repaired in the English guide's glossary table. Every wording change stays a logged edit
in edits/*.json.
"""
from __future__ import annotations

import re

NOTE = ("structure checked against the canonical layout, no wording changed; English and Spanish manuscripts: bold contents line becomes the "
        "“Contents” heading; French manuscript: the ten `---` rules between chapters are dropped and the eighteen glossary entries move to one "
        "line each (“**Term** : definition”) as in English and Spanish; English manuscript: the three promises of chapter 13 become a numbered "
        "list as in French and Spanish, and “Pagne” is placed before “Pirogue” in the glossary (alphabetical order, as in French and Spanish); "
        "English guide: same alphabetical fix in the glossary table")

CONTENTS = {"en": "**Contents**", "es": "**Índice**"}
PROMISES = ("**Listen.**", "**Pass.**", "**Play fair.**")


def _paras(text: str) -> list[str]:
    return [p.strip("\n") for p in re.split(r"\n\s*\n", text.replace("\r\n", "\n")) if p.strip()]


def _contents_heading(paras: list[str], lang: str) -> list[str]:
    want = CONTENTS[lang]
    idx = [i for i, p in enumerate(paras) if p.strip() == want]
    if len(idx) != 1:
        raise SystemExit(f"normalize: expected one {want} line in the {lang} manuscript, found {len(idx)}")
    paras[idx[0]] = "## " + want.strip("*")
    return paras


def _fr_rules(paras: list[str]) -> list[str]:
    n = sum(1 for p in paras if p.strip() == "---")
    if n != 10:
        raise SystemExit(f"normalize: expected 10 chapter rules in the French manuscript, found {n}")
    return [p for p in paras if p.strip() != "---"]


def _fr_glossary(paras: list[str]) -> list[str]:
    a = next(i for i, p in enumerate(paras) if p.startswith("## Glossaire"))
    b = next(i for i, p in enumerate(paras) if p.startswith("## Note documentaire"))
    n = 0
    for i in range(a + 1, b):
        m = re.match(r"^\*\*([^*\n]+)\*\*[ ]*\n(.+)$", paras[i], re.S)   # the mechanical cleanup has already trimmed the hard-break spaces
        if m:
            paras[i] = f"**{m.group(1)}** : {m.group(2).strip()}"
            n += 1
    if n != 18:
        raise SystemExit(f"normalize: expected 18 glossary entries in the French manuscript, found {n}")
    return paras


def _en_promises(paras: list[str]) -> list[str]:
    i = next((k for k, p in enumerate(paras) if p.startswith(PROMISES[0])), None)
    if i is None or [paras[i + k].startswith(PROMISES[k]) for k in range(3)] != [True] * 3:
        raise SystemExit("normalize: the three promises of chapter 13 were not found in the English manuscript")
    items = [f"{k}. {paras[i + k - 1]}" for k in range(1, 4)]
    return paras[:i] + ["\n".join(items)] + paras[i + 3:]


def _en_pagne_before_pirogue(paras: list[str]) -> list[str]:
    i = next((k for k, p in enumerate(paras) if p.startswith("**Pirogue**")), None)
    if i is None or not paras[i + 1].startswith("**Pagne**"):
        raise SystemExit("normalize: expected “Pirogue” followed by “Pagne” in the English glossary")
    paras[i], paras[i + 1] = paras[i + 1], paras[i]
    return paras


def normalize_manuscript(text: str, lang: str) -> str:
    paras = _paras(text)
    if lang in CONTENTS:
        paras = _contents_heading(paras, lang)
    if lang == "fr":
        paras = _fr_glossary(_fr_rules(paras))
    if lang == "en":
        paras = _en_pagne_before_pirogue(_en_promises(paras))
    return "\n\n".join(paras) + "\n"


def normalize_guide(text: str, lang: str) -> str:
    if lang != "en":
        return text
    lines = text.split("\n")
    i = next((k for k, l in enumerate(lines) if l.startswith("| **Pirogue** |")), None)
    if i is None or not lines[i + 1].startswith("| **Pagne** |"):
        raise SystemExit("normalize: expected “Pirogue” then “Pagne” rows in the English guide glossary")
    lines[i], lines[i + 1] = lines[i + 1], lines[i]
    return "\n".join(lines)


def normalize(text: str, lang: str, which: str = "manuscript") -> str:
    text = text.replace("...", "…")           # typographic ellipsis (no-op when the files already use …)
    return normalize_manuscript(text, lang) if which == "manuscript" else normalize_guide(text, lang)
